module.exports = {
  LOTTERY_SERIE_LENGTH: 6,
  LOCAL_PORT: 3000,
  KQXS_ORIGIN: "https://minhngoc.net.vn/getkqxs/da-nang.js",
  provinceCode: new Map([
    ['Miền Nam', 'mien-nam'],
    ['Miền Trung', 'mien-trung'],
    ['Miền Bắc', 'mien-bac'],
    ['An Giang', 'an-giang'],
    ['Bình Dương', 'binh-duong'],
    ['Bình Định', 'binh-dinh'],
    ['Bạc Liêu', 'bac-lieu'],
    ['Bình Phước', 'binh-phuoc'],
    ['Bến Tre', 'ben-tre'],
    ['Bình Thuận', 'binh-thuan'],
    ['Cà Mau', 'ca-mau'],
    ['Cần Thơ', 'can-tho'],
    ['Đắc Lắc', 'dak-lak'],
    ['Đồng Nai', 'dong-nai'],
    ['Đà Nẵng', 'da-nang'],
    ['Đắc Nông', 'dak-nong'],
    ['Đồng Tháp', 'dong-thap'],
    ['Gia Lai', 'gia-lai'],
    ['TP.HCM', 'tphcm'],
    ['Hậu Giang', 'hau-giang'],
    ['Kiên Giang', 'kien-giang'],
    ['Khánh Hòa', 'khanh-hoa'],
    ['Kon Tum', 'kon-tum'],
    ['Long An', 'long-an'],
    ['Lâm Đồng', 'lam-dong'],
    ['Ninh Thuận', 'ninh-thuan'],
    ['Phú Yên', 'phu-yen'],
    ['Quảng Bình', 'quang-binh'],
    ['Quảng Ngãi', 'quang-ngai'],
    ['Quảng Nam', 'quang-nam'],
    ['Quảng Trị', 'quang-tri'],
    ['Sóc Trăng', 'soc-trang'],
    ['Tiền Giang', 'tien-giang'],
    ['Tây Ninh', 'tay-ninh'],
    ['Thừa Thiên Huế', 'thua-thien-hue'],
    ['Trà Vinh', 'tra-vinh'],
    ['Vĩnh Long', 'vinh-long'],
    ['Vũng Tàu', 'vung-tau']
  ]),
  // code defined in https://xoso.com.vn/
  provinceXs: new Map([
    ['mien-nam', 'xsmn'],
    ['mien-trung', 'xsmt'],
    ['mien-bac', 'xsmb'],
    ['an-giang', 'xsag'],
    ['binh-duong', 'xsbd'],
    ['binh-dinh', 'xsbdi'],
    ['bac-lieu', 'xsbl'],
    ['binh-phuoc', 'xsbp'],
    ['ben-tre', 'xsbt'],
    ['binh-thuan', 'xsbth'],
    ['ca-mau', 'xscm'],
    ['can-tho', 'xsct'],
    ['dak-lak', 'xsdlk'],
    ['dong-nai', 'xsdn'],
    ['da-nang', 'xsdna'],
    ['dak-nong', 'xs'],
    ['dong-thap', 'xsdt'],
    ['gia-lai', 'xsgl'],
    ['tphcm', 'xstphcm'],
    ['hau-giang', 'xshg'],
    ['kien-giang', 'xskg'],
    ['khanh-hoa', 'xskh'],
    ['kon-tum', 'xskt'],
    ['long-an', 'xsla'],
    ['lam-dong', 'xsld'],
    ['ninh-thuan', 'xsnt'],
    ['phu-yen', 'xspy'],
    ['quang-binh', 'xsqb'],
    ['quang-ngai', 'xsqng'],
    ['quang-nam', 'xsqna'],
    ['quang-tri', 'xsqt'],
    ['soc-trang', 'xsst'],
    ['tien-giang', 'xstg'],
    ['tay-ninh', 'xstn'],
    ['thua-thien-hue', 'xstth'],
    ['tra-vinh', 'xs'],
    ['vinh-long', 'xsvl'],
    ['vung-tau', 'xsvt']
  ]),
  API_ENDPOINT: 'https://xoso.com.vn/'
}